### ISSUE TITLE
Retrain the model?

### ISSUE THREAD

**Issue by ZeroDesigner** [xichengeva/DeepGlycanSite#10]
I am retraining the model.

When I directly run the model , I met the problem.

Can you offer a small dataset to show how to train ?

''' (DeepGlycanSite) jsu@ml-apus:/data1/jsu/Software/DeepGlycanSite$ python DeepGlycanSite_lig.py --conf P2Y14_example/hparams.yaml --output-path DeepGlycanSite_lig

/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch_sparse/tensor.py:5: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.21.0)
  import scipy.sparse
{'conf': None, 'batch_size': 4, 'seed': 0, 'dropout_rate': 0.1468558190536503, 'hidden_dim': 256, 'residual_layers': 21, 'num_heads_visnet': 16, 'num_heads_Transformer': 8, 'num_encoder_layers': 7, 'num_decoder_layers': 7, 'num_layers_visnet': 11, 'num_rbf': 64, 'lmax': 2, 'trainable_rbf': False, 'vecnorm_trainable': False, 'lr': 2.7505276550136346e-05, 'weight_decay': 4.02688016652314e-05, 'lr_factor': 0.794620587116932, 'lr_patience': 4, 'lr_min': 1.6535440079417535e-08, 'loss_alpha': 0.3214576710484223, 'loss_gamma': 3.289689652508993, 'proj_name': 'visnet', 'output_path': 'DeepGlycanSite_lig', 'train_set': None, 'val_set': None, 'results_dir': None}
Global seed set to 0
Traceback (most recent call last):
  File "/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch/serialization.py", line 348, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/jsu/Software/DeepGlycanSite/DeepGlycanSite_lig.py", line 319, in <module>
    main()
  File "/data1/jsu/Software/DeepGlycanSite/DeepGlycanSite_lig.py", line 288, in main
    dataset0 = torch.load(args['train_set'])
  File "/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch/serialization.py", line 275, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch/serialization.py", line 260, in __init__
    _check_seekable(buffer)
  File "/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch/serialization.py", line 351, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/jsu/work/Software/miniconda/envs/DeepGlycanSite/lib/python3.9/site-packages/torch/serialization.py", line 344, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.'''

**Comment by Xinheng-He** [comment]
We are preparing the dataset for release. Currently, it seems to be a problem with pytorch version or the data is not prepared\loaded. You can check the test result folder with *.pt file, such file follows the format of the training set and you can use it for training.
Thanks for your focus on our work.
