### ISSUE TITLE
Issue with pip install "fair-esm[emsfold]" during setup

### ISSUE THREAD

**Issue by emmasheriff** [xichengeva/DeepGlycanSite#18]
Hi -- can anyone help me with this error I get after running the `pip install "fair-esm[esmfold]"` command? I don't have a lot of experience in using the command line, but my university's IT Help Desk also encountered errors with the when trying to help me troubleshoot. I am following the instructions for CPU setup. Thank you!

```
(DeepGlycanSite) C:\Hyapp\Anaconda3-2023.07-2\DeepGlycanSite>pip install "fair-esm[esmfold]"
Collecting fair-esm[esmfold]
  Downloading fair_esm-2.0.0-py3-none-any.whl.metadata (37 kB)
Collecting biopython (from fair-esm[esmfold])
  Downloading biopython-1.84-cp39-cp39-win_amd64.whl.metadata (13 kB)
Collecting deepspeed==0.5.9 (from fair-esm[esmfold])
  Downloading deepspeed-0.5.9.tar.gz (510 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sheriffe\AppData\Local\Temp\pip-install-ub3m366x\deepspeed_c2dac8747f7b4281a3a4c5535f20ba33\setup.py", line 138, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\sheriffe\AppData\Local\Temp\pip-install-ub3m366x\deepspeed_c2dac8747f7b4281a3a4c5535f20ba33\setup.py", line 43, in abort
          assert False, msg
      AssertionError: Unable to pre-compile cpu_adam
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
      ←[93m [WARNING] ←[0m One can disable cpu_adam with DS_BUILD_CPU_ADAM=0
      ←[31m [ERROR] ←[0m Unable to pre-compile cpu_adam
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Xinheng-He** [comment]
Use Linux for dealing with it or test using our server https://www.glycaninsight.cn

**Comment by emmasheriff** [comment]
The server is super helpful!! Thank you
